language: generic

script:
  - bash ./deploy.sh

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
  - ENCRYPTION_LABEL: "45a211a6d795"
  - COMMIT_AUTHOR_EMAIL: "d@domenic.me"
